name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: GitHub raw url
				id: convert-to-url
				uses: ActionCloud/github-raw-url@v1
				with:
					github-url: https://github.com/vinsdragonis/vinsdragonis/blob/main/banner%20-%20open%20source%20(1).png
				run: echo '${{ steps.convert-to-url.outputs.raw-url }}'
